# 256 colur and true colour
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

########## Plugins ##########

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# theme
#set -g @plugin 'seebi/tmux-colors-solarized'
#set -g @colors-solarized 'dark'
#set -g @plugin "arcticicestudio/nord-tmux"

########## General Settings ##########

set -g set-clipboard on
set -g detach-on-destroy off
set -g mouse on
set -g status-interval 3

### Style

gray_light="#D8DEE9"
gray_medium="4C566A"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-position top
set -g status-left-length 80
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "

### Keybindings

# quickly reload tmux conf
bind r source-file ~/.tmux.conf \; display " "

# set prefix to control-space
unbind C-b
set -g prefix C-Space
bind c-Space send-prefix

# Shift+Alt vim keys to switch windows
# have to set option -> Esc+ in iTerm for this
bind -n M-H previous-window
bind -n M-L next-window

# set vi-mode, bindings for copy text
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

### Behaviour

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# open panes in pwd instead of ~
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
